### ISSUE TITLE
A 404 page would be nice

### ISSUE THREAD

**Issue by TVke** [botman/docs#76]
When reading the new docs from 2.0 and then switching to 1.5 gives the default laravel error:
<img width="1439" alt="schermafbeelding 2018-04-06 om 10 32 29" src="https://user-images.githubusercontent.com/15680337/38411233-e7766f74-3986-11e8-8e22-db64591fbaa5.png">

It would be nice to have a laravel docs like behaviour there:
<img width="1437" alt="schermafbeelding 2018-04-06 om 10 33 10" src="https://user-images.githubusercontent.com/15680337/38411240-e9767558-3986-11e8-97b3-817339608883.png">

**Comment by christophrumpel** [comment]
Hey @TVke , you are right this would be a nice addition. We would accept a PR :-)
